name: Block Invalid Release Branches

on:
  workflow_call:
    inputs:
      head_ref:
        description: "Name des Head-Branches (github.head_ref)"
        required: true
        type: string

jobs:
  block-invalid-release-pr:
    if: github.event.action == 'ready_for_review' || (github.event.action == 'synchronize' && github.event.pull_request.draft == false)

    runs-on: ubuntu-latest

    steps:
      - name: Check branch naming convention
        run: |
          branch="${{ inputs.head_ref }}"

          if [[ ! "$branch" =~ ^R[0-9]{2}($|-|/) ]]; then
            echo "::error title=Invalid branch name::"
            echo "Dieser Pull Request darf **nicht** in master gemerged werden!"
            echo ""
            echo "Erlaubte Branches: R01, R02, ..., R99"
            echo "Aktueller Branch: $branch"
            exit 1
          fi

          echo "Branch-Name OK: $branch"
