name: Create Release

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number
      pr_body:
        required: false
        type: string
        default: ''

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ inputs.branch_name }}"
          name: ${{ inputs.branch_name }}
          body: |
            Automated release from branch **${{ inputs.branch_name }}**
            
            Merged into `master` via PR #${{ inputs.pr_number }}
            
            ${{ inputs.pr_body }}
          draft: false
          prerelease: false
          generate_release_notes: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
