name: Reusable - Remove Trailing Whitespace

on:
  workflow_call:
    inputs:
      script-path:
        description: 'Path to the script in the reusable repository'
        required: false
        default: '.github/scripts/remove_trailing_whitespaces.py'
        type: string
      commit-message:
        description: 'Commit message'
        required: false
        default: 'chore: remove trailing whitespace'
        type: string
      python-version:
        description: 'Python version'
        required: false
        default: '3.12'
        type: string
      reusable-repo-ref:
        description: 'Branch or tag of the reusable repository'
        required: false
        default: 'latest'
        type: string

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          ref: latest
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout reusable workflows repository
        uses: actions/checkout@v4
        with:
          repository: salva133/My-Workflows
          path: reusable-workflows
          ref: ${{ inputs.reusable-repo-ref }}
          sparse-checkout: |
            .github/scripts/remove_trailing_whitespaces.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Remove trailing whitespace
        run: python reusable-workflows/${{ inputs.script-path }} .

      - name: Commit & Push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: ${{ inputs.commit-message }}
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          branch: latest
          file_pattern: |
            **/*.txt
            **/*.yml
