name: Trim Trailing Whitespace

on:
  workflow_call:

permissions:
  contents: write

concurrency:
  group: trim-whitespace-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  trim:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Remove trailing whitespace
        run: |
          git ls-files -z --cached --exclude-standard -- '*.txt' '*.yml' |
          xargs -0 sed -i 's/[[:space:]]*$//'

      - uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          commit_message: "style: trim trailing whitespace"
          branch: ${{ github.head_ref || github.ref_name }}
